#############################################################################
# Makefile for building: Pencil
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Oct 21 17:32:48 2012
# Project:  pencil.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile pencil.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Isrc -Isrc/external/flash -Isrc/external/linux -Isrc/external/macosx -Isrc/external/win32 -Isrc/graphics -Isrc/graphics/bitmap -Isrc/graphics/vector -Isrc/interface -Isrc/structure -I. -Iliblinux -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -Lliblinux -lming -lpng -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/external/flash/flash.cpp \
		src/graphics/bitmap/blur.cpp \
		src/graphics/bitmap/bitmapimage.cpp \
		src/graphics/vector/bezierarea.cpp \
		src/graphics/vector/beziercurve.cpp \
		src/graphics/vector/colourref.cpp \
		src/graphics/vector/gradient.cpp \
		src/graphics/vector/vectorimage.cpp \
		src/graphics/vector/vertexref.cpp \
		src/structure/layer.cpp \
		src/structure/layerbitmap.cpp \
		src/structure/layercamera.cpp \
		src/structure/layerimage.cpp \
		src/structure/layersound.cpp \
		src/structure/layervector.cpp \
		src/structure/object.cpp \
		src/interface/editor.cpp \
		src/interface/mainwindow.cpp \
		src/interface/palette.cpp \
		src/interface/preferences.cpp \
		src/interface/scribblearea.cpp \
		src/interface/timeline.cpp \
		src/interface/timecontrols.cpp \
		src/interface/toolset.cpp \
		src/main.cpp \
		src/external/linux/linux.cpp moc_layer.cpp \
		moc_layerbitmap.cpp \
		moc_layercamera.cpp \
		moc_layerimage.cpp \
		moc_layersound.cpp \
		moc_layervector.cpp \
		moc_object.cpp \
		moc_editor.cpp \
		moc_mainwindow.cpp \
		moc_palette.cpp \
		moc_preferences.cpp \
		moc_scribblearea.cpp \
		moc_timeline.cpp \
		moc_timecontrols.cpp \
		moc_toolset.cpp \
		qrc_pencil.cpp
OBJECTS       = flash.o \
		blur.o \
		bitmapimage.o \
		bezierarea.o \
		beziercurve.o \
		colourref.o \
		gradient.o \
		vectorimage.o \
		vertexref.o \
		layer.o \
		layerbitmap.o \
		layercamera.o \
		layerimage.o \
		layersound.o \
		layervector.o \
		object.o \
		editor.o \
		mainwindow.o \
		palette.o \
		preferences.o \
		scribblearea.o \
		timeline.o \
		timecontrols.o \
		toolset.o \
		main.o \
		linux.o \
		moc_layer.o \
		moc_layerbitmap.o \
		moc_layercamera.o \
		moc_layerimage.o \
		moc_layersound.o \
		moc_layervector.o \
		moc_object.o \
		moc_editor.o \
		moc_mainwindow.o \
		moc_palette.o \
		moc_preferences.o \
		moc_scribblearea.o \
		moc_timeline.o \
		moc_timecontrols.o \
		moc_toolset.o \
		qrc_pencil.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		pencil.pro
QMAKE_TARGET  = Pencil
DESTDIR       = 
TARGET        = Pencil

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pencil.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile pencil.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile pencil.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pencil1.0.0 || $(MKDIR) .tmp/Pencil1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pencil1.0.0/ && $(COPY_FILE) --parents src/interfaces.h src/external/flash/flash.h src/graphics/bitmap/bitmapimage.h src/graphics/vector/bezierarea.h src/graphics/vector/beziercurve.h src/graphics/vector/colourref.h src/graphics/vector/gradient.h src/graphics/vector/vectorimage.h src/graphics/vector/vertexref.h src/structure/layer.h src/structure/layerbitmap.h src/structure/layercamera.h src/structure/layerimage.h src/structure/layersound.h src/structure/layervector.h src/structure/object.h src/interface/editor.h src/interface/mainwindow.h src/interface/palette.h src/interface/preferences.h src/interface/scribblearea.h src/interface/timeline.h src/interface/timecontrols.h src/interface/toolset.h .tmp/Pencil1.0.0/ && $(COPY_FILE) --parents pencil.qrc .tmp/Pencil1.0.0/ && $(COPY_FILE) --parents src/external/flash/flash.cpp src/graphics/bitmap/blur.cpp src/graphics/bitmap/bitmapimage.cpp src/graphics/vector/bezierarea.cpp src/graphics/vector/beziercurve.cpp src/graphics/vector/colourref.cpp src/graphics/vector/gradient.cpp src/graphics/vector/vectorimage.cpp src/graphics/vector/vertexref.cpp src/structure/layer.cpp src/structure/layerbitmap.cpp src/structure/layercamera.cpp src/structure/layerimage.cpp src/structure/layersound.cpp src/structure/layervector.cpp src/structure/object.cpp src/interface/editor.cpp src/interface/mainwindow.cpp src/interface/palette.cpp src/interface/preferences.cpp src/interface/scribblearea.cpp src/interface/timeline.cpp src/interface/timecontrols.cpp src/interface/toolset.cpp src/main.cpp src/external/linux/linux.cpp .tmp/Pencil1.0.0/ && (cd `dirname .tmp/Pencil1.0.0` && $(TAR) Pencil1.0.0.tar Pencil1.0.0 && $(COMPRESS) Pencil1.0.0.tar) && $(MOVE) `dirname .tmp/Pencil1.0.0`/Pencil1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pencil1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_layer.cpp moc_layerbitmap.cpp moc_layercamera.cpp moc_layerimage.cpp moc_layersound.cpp moc_layervector.cpp moc_object.cpp moc_editor.cpp moc_mainwindow.cpp moc_palette.cpp moc_preferences.cpp moc_scribblearea.cpp moc_timeline.cpp moc_timecontrols.cpp moc_toolset.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_layer.cpp moc_layerbitmap.cpp moc_layercamera.cpp moc_layerimage.cpp moc_layersound.cpp moc_layervector.cpp moc_object.cpp moc_editor.cpp moc_mainwindow.cpp moc_palette.cpp moc_preferences.cpp moc_scribblearea.cpp moc_timeline.cpp moc_timecontrols.cpp moc_toolset.cpp
moc_layer.cpp: src/structure/layer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layer.h -o moc_layer.cpp

moc_layerbitmap.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/layerbitmap.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layerbitmap.h -o moc_layerbitmap.cpp

moc_layercamera.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/layercamera.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layercamera.h -o moc_layercamera.cpp

moc_layerimage.cpp: src/structure/layer.h \
		src/structure/layerimage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layerimage.h -o moc_layerimage.cpp

moc_layersound.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/layersound.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layersound.h -o moc_layersound.cpp

moc_layervector.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/layervector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layervector.h -o moc_layervector.cpp

moc_object.cpp: src/structure/layer.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/structure/layervector.h \
		src/structure/object.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/object.h -o moc_object.cpp

moc_editor.cpp: src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interface/editor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/editor.h -o moc_editor.cpp

moc_mainwindow.cpp: src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interface/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/mainwindow.h -o moc_mainwindow.cpp

moc_palette.cpp: src/interface/toolset.h \
		src/interface/palette.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/palette.h -o moc_palette.cpp

moc_preferences.cpp: src/interface/preferences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/preferences.h -o moc_preferences.cpp

moc_scribblearea.cpp: src/interface/scribblearea.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/scribblearea.h -o moc_scribblearea.cpp

moc_timeline.cpp: src/interface/toolset.h \
		src/interface/timeline.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/timeline.h -o moc_timeline.cpp

moc_timecontrols.cpp: src/interface/timecontrols.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/timecontrols.h -o moc_timecontrols.cpp

moc_toolset.cpp: src/interface/toolset.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/toolset.h -o moc_toolset.cpp

compiler_rcc_make_all: qrc_pencil.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pencil.cpp
qrc_pencil.cpp: pencil.qrc \
		background/weave.jpg \
		background/dots.png \
		icons/select.png \
		icons/pen.png \
		icons/brush.png \
		icons/bucketTool.png \
		icons/add.png \
		icons/polyline.png \
		icons/arrow.png \
		icons/logo.png \
		icons/layer-sound.png \
		icons/eraser2.png \
		icons/move.png \
		icons/prefs-files.png \
		icons/icon.png \
		icons/prefstimeline.png \
		icons/aqua.png \
		icons/eyedropper.png \
		icons/smudge.png \
		icons/layer-vector.png \
		icons/magnify.png \
		icons/pencil2.png \
		icons/onionNext.png \
		icons/thinlines5.png \
		icons/layer-bitmap.png \
		icons/onionPrev.png \
		icons/house.png \
		icons/hand.png \
		icons/bucket.png \
		icons/prefspencil.png \
		icons/clear.png \
		icons/mirror.png \
		icons/layer-camera.png \
		icons/eraser.png \
		icons/outlines5.png \
		icons/remove.png \
		icons/controls/separator.png \
		icons/controls/play.png \
		icons/controls/sound.png \
		icons/controls/loop.png
	/usr/bin/rcc -name pencil pencil.qrc -o qrc_pencil.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

flash.o: src/external/flash/flash.cpp src/external/flash/flash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flash.o src/external/flash/flash.cpp

blur.o: src/graphics/bitmap/blur.cpp src/graphics/bitmap/blur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blur.o src/graphics/bitmap/blur.cpp

bitmapimage.o: src/graphics/bitmap/bitmapimage.cpp src/graphics/bitmap/bitmapimage.h \
		src/graphics/bitmap/blur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitmapimage.o src/graphics/bitmap/bitmapimage.cpp

bezierarea.o: src/graphics/vector/bezierarea.cpp src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bezierarea.o src/graphics/vector/bezierarea.cpp

beziercurve.o: src/graphics/vector/beziercurve.cpp src/graphics/vector/beziercurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beziercurve.o src/graphics/vector/beziercurve.cpp

colourref.o: src/graphics/vector/colourref.cpp src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colourref.o src/graphics/vector/colourref.cpp

gradient.o: src/graphics/vector/gradient.cpp src/graphics/vector/gradient.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradient.o src/graphics/vector/gradient.cpp

vectorimage.o: src/graphics/vector/vectorimage.cpp src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/gradient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vectorimage.o src/graphics/vector/vectorimage.cpp

vertexref.o: src/graphics/vector/vertexref.cpp src/graphics/vector/vertexref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vertexref.o src/graphics/vector/vertexref.cpp

layer.o: src/structure/layer.cpp src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/structure/layervector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layer.o src/structure/layer.cpp

layerbitmap.o: src/structure/layerbitmap.cpp src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/structure/layer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layerbitmap.o src/structure/layerbitmap.cpp

layercamera.o: src/structure/layercamera.cpp src/structure/layercamera.h \
		src/structure/layerimage.h \
		src/structure/layer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layercamera.o src/structure/layercamera.cpp

layerimage.o: src/structure/layerimage.cpp src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/structure/layervector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layerimage.o src/structure/layerimage.cpp

layersound.o: src/structure/layersound.cpp src/structure/layersound.h \
		src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/structure/layervector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layersound.o src/structure/layersound.cpp

layervector.o: src/structure/layervector.cpp src/structure/layervector.h \
		src/structure/layerimage.h \
		src/structure/layer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layervector.o src/structure/layervector.cpp

object.o: src/structure/object.cpp src/structure/object.h \
		src/structure/layer.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/structure/layervector.h \
		src/structure/layersound.h \
		src/structure/layercamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o src/structure/object.cpp

editor.o: src/interface/editor.cpp src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h \
		src/interface/palette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o src/interface/editor.cpp

mainwindow.o: src/interface/mainwindow.cpp src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interface/mainwindow.h \
		src/interfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/interface/mainwindow.cpp

palette.o: src/interface/palette.cpp src/interface/palette.h \
		src/interface/toolset.h \
		src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o palette.o src/interface/palette.cpp

preferences.o: src/interface/preferences.cpp src/interface/preferences.h \
		src/interface/scribblearea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o src/interface/preferences.cpp

scribblearea.o: src/interface/scribblearea.cpp src/interface/scribblearea.h \
		src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/preferences.h \
		src/interface/palette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scribblearea.o src/interface/scribblearea.cpp

timeline.o: src/interface/timeline.cpp src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/editor.h \
		src/interface/scribblearea.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interface/timecontrols.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timeline.o src/interface/timeline.cpp

timecontrols.o: src/interface/timecontrols.cpp src/interface/timecontrols.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timecontrols.o src/interface/timecontrols.cpp

toolset.o: src/interface/toolset.cpp src/interface/toolset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolset.o src/interface/toolset.cpp

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

linux.o: src/external/linux/linux.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux.o src/external/linux/linux.cpp

moc_layer.o: moc_layer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layer.o moc_layer.cpp

moc_layerbitmap.o: moc_layerbitmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layerbitmap.o moc_layerbitmap.cpp

moc_layercamera.o: moc_layercamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layercamera.o moc_layercamera.cpp

moc_layerimage.o: moc_layerimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layerimage.o moc_layerimage.cpp

moc_layersound.o: moc_layersound.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layersound.o moc_layersound.cpp

moc_layervector.o: moc_layervector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layervector.o moc_layervector.cpp

moc_object.o: moc_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_object.o moc_object.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_palette.o: moc_palette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_palette.o moc_palette.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_scribblearea.o: moc_scribblearea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scribblearea.o moc_scribblearea.cpp

moc_timeline.o: moc_timeline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timeline.o moc_timeline.cpp

moc_timecontrols.o: moc_timecontrols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timecontrols.o moc_timecontrols.cpp

moc_toolset.o: moc_toolset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolset.o moc_toolset.cpp

qrc_pencil.o: qrc_pencil.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pencil.o qrc_pencil.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

